### ISSUE TITLE
brick En Rom J2 Prime

### ISSUE THREAD

**Issue by KanekiKenOficial** [almondnguyen/android_device_samsung_grandppltedx#14]
[There]([url](url)) is a problem that I have and it is that when installing its latest compilation of lineage-14.1-20230707 after installing it, either the device is downloaded or it turns off, when it is turned on it stays frozen in the samsung logo
![IMG_20230721_012148](https://github.com/almondnguyen/android_device_samsung_grandppltedx/assets/139829868/7cecde12-f230-47ba-b54d-5deab6978d48)
![IMG_20230721_012147](https://github.com/almondnguyen/android_device_samsung_grandppltedx/assets/139829868/93fbb02f-c23b-453f-8ccb-97ac64ca807d)
![IMG_20230721_012146](https://github.com/almondnguyen/android_device_samsung_grandppltedx/assets/139829868/ba937f57-9562-4f85-a431-5c6ca1e8d7fe)
![IMG_20230721_012145](https://github.com/almondnguyen/android_device_samsung_grandppltedx/assets/139829868/9bf9c467-c995-4f49-ba1b-11d8c17493ce)
![IMG_20230721_012143](https://github.com/almondnguyen/android_device_samsung_grandppltedx/assets/139829868/3775c7d8-d500-492f-9d77-6bbc303acec1)

>

**Comment by almondnguyen** [comment]
yea the 0707 version has a kernel dying bug on sudden/improper shutdown. The fix is to go to recovery and reboot to system. I'll close this now since I removed the 0707 version.
