### ISSUE TITLE
Feature request: Use LineageOS's LiveDisplay for MediaTek

### ISSUE THREAD

**Issue by bmndc** [almondnguyen/android_device_samsung_grandppltedx#7]
https://github.com/LineageOS/android_hardware_mediatek

**Comment by almondnguyen** [comment]
on it!~

**Comment by almondnguyen** [comment]
I just read it today. This one is for LineageOS 17.1 (literally the branch name LOL).

While the issue is there, this one isn't anymore relevant so I'm closing!~
Thank you for the effort nonetheless.
