### ISSUE TITLE
Some issues that are still occurring.

### ISSUE THREAD

**Issue by Brasil150** [almondnguyen/android_device_samsung_grandppltedx#9]
Hello, I'm using your port and it's really working very well, however, some problems are still occurring but I would like to highlight these:

- Battery life very low.
- Freeze and random shutdown of the smartphone.
- Log spam to \Android\data\

I'm aware of the battery life and log spam issue, but I thought the freezing issue was fixed.

![a6040108-ba92-4320-a664-4e8011b729ea](https://user-images.githubusercontent.com/55663598/159095287-e684c104-e08f-46c2-bdbf-14bf6c225f31.jpg)
Just for information here is a print of the battery life that reaches a maximum of 8 hours (WITHOUT USING).

Another thing that is quite bad is not being able to recharge the cell phone with it off because if the battery is very low the chance of turning it on is very low.
Congratulations on fixing the RIL, that's a big step forward!

**Comment by Hassanarshad222888** [comment]
Give me link of this ROM plz may I can help you

**Comment by Brasil150** [comment]
Not necessary, battery life has been greatly improved in other updates but
in case you're still interested, here it is:
https://forum.xda-developers.com/t/rom-g532x-7-1-2-beta-lineageos-14-1-for-galaxy-j2-prime.3946388/

Em qua., 1 de jun. de 2022 às 13:03, Hassanarshad222888 <
***@***.***> escreveu:

**Comment by Hassanarshad222888** [comment]
I tried this  ROM, sims not working

**Comment by Brasil150** [comment]
Estanho, no meu está normal. Verificou se o IMEI está ok? O meu modelo é o
G532MT.

Em qua, 1 de jun de 2022 22:45, Hassanarshad222888 ***@***.***>
escreveu:

**Comment by almondnguyen** [comment]
sorry late reply, deadline killing me



> I tried this ROM, sims not working

SIM should be working correctly though. If you have 2 SIM, make sure you've done the instruction (to set both SIM to 2G first, then the main data SIM to 4G/3G).

E: suppose I won't need to answer the main post. First two still not fixed, third should be fixed by now tho.

**Comment by Hassanarshad222888** [comment]
When you will compile lineage os 15.1 for Grand prime plus.I am waiting.

**Comment by Hassanarshad222888** [comment]
Plz add support for project Treble in lineage os 15.1 to get lifetime android updates from google

**Comment by Hassanarshad222888** [comment]
SMG-532F always show Sim card not detected on lineage 14.1 Even IMEI is Registered

**Comment by Hassanarshad222888** [comment]
https://user-images.githubusercontent.com/94609593/171881082-d28666f6-f78a-48df-8418-5c6e6490d4b5.mp4

I separate vendor partition for project Treble but after reboot , vendor partition removes

**Comment by almondnguyen** [comment]
> SMG-532F always show Sim card not detected on lineage 14.1 Even IMEI is Registered 

y'know, screenshots would be much more helpful........

screenshot in About Phone, show build number



> {all the things about LineageOS 15.1 or Treble}

_meh, do it yourself then. So you'll know the troubles I have._

(please do the research beforehand, Treble isn't that magical. Even 9 GSI didn't boot on Treble 8 on many devices....)

**Comment by Hassanarshad222888** [comment]
I made Treblizer flashed successfully in Twrp but not works check code of in binary script in META-INF folder:https://github.com/Hassanarshad222888/ProjectTreble_J2-Prime

**Comment by Hassanarshad222888** [comment]
Let me contribute in your work plz

**Comment by Hassanarshad222888** [comment]
Waiting for your reply

**Comment by almondnguyen** [comment]
- One, you are spamming in an issue thread, about topic not at all related to that issue.

- Two, you are spamming my mailbox. When
> deadline killing me

- Three, sgdisk doesn't work on this device. PIT is the only way.
> please do the research beforehand.

- Four, you can fork my project no problemo. You can do whatever with your fork.

- Five, read everything. I mean everything.

- Six and finally, please have some manner and common sense. Everyone has their life.


Sorry to the OP for letting this get out of hand. If you need addressing again please create new issue instead!~

**Comment by Hassanarshad222888** [comment]
Ok I fix issues by own Enjoy your life.these all were my last comments.be happy in your life ,no more comments from now😭😭

**Comment by Hassanarshad222888** [comment]
You hurt my feelings😭
